# This notebook creates Fig 1 of the paper

Includes:
- figure
-

In [66]:
import pandas as pd
import os
import numpy as np

df = pd.read_csv('../dados_raw/checklist-species-29Abr2026.csv')

# Filter for taxonRank not genus
df = df[df['taxonRank'].str.lower() != 'genus'].reset_index(drop=True)
df.shape
df.head()

,taxonID,taxonID_serial,scientificName,acceptedNameUsage,acceptedNameUsageID,kingdom,phylum,class,order,family,genus,specificEpithet,infraSpecificEpithet,scientificNameAuthorship,taxonRank,nameAccordingTo,taxonRemarks,nomenclaturalStatus,taxonomicStatus
0,ed4227734ed75d343320b6a5fd16ce57,NaN,Heterodermia tremulans (Müll. Arg.) W.L. Culb.,NaN,NaN,Fungi,Ascomycota,Lecanoromycetes,Caliciales,Physciaceae,Heterodermia,tremulans,NaN,(Müll. Arg.) W.L. Culb.,species,NaN,NaN,NaN,accepted
1,71ed64cfe69b4dc8b57d08c1e92b9693,1.0,Tetramelas thiopolizus (Nyl.) Giralt & P. Clerc,NaN,NaN,Fungi,Ascomycota,Lecanoromycetes,Caliciales,Caliciaceae,Tetramelas,thiopolizus,NaN,(Nyl.) Giralt & P. Clerc,species,NaN,NaN,NaN,accepted
2,2c6096dc36724669880dc1c58b15c8b7,2.0,Verrucaria gemmifera Taylor,NaN,NaN,Fungi,Ascomycota,Eurotiomycetes,Verrucariales,Verrucariaceae,Verrucaria,gemmifera,NaN,Taylor,species,NaN,NaN,NaN,accepted
3,d42c0868e238baac78bb55b1c3f400b6,3.0,Abrothallus bertianus De Not.,NaN,NaN,Fungi,Ascomycota,Dothideomycetes,Abrothallales,Abrothallaceae,Abrothallus,bertianus,NaN,De Not.,species,"Suija, A.; Hawksworth, D.L. & Pérez-Ortega, S....",NaN,NaN,accepted
4,8a26f1cb1252fcdbe8ef9d3c12cef3d2,4.0,Abrothallus caerulescens I. Kotte,NaN,NaN,Fungi,Ascomycota,Dothideomycetes,Abrothallales,Abrothallaceae,Abrothallus,caerulescens,NaN,I.Kotte,species,"Suija, A.; Hawksworth, D.L. & Pérez-Ortega, S....",NaN,NaN,accepted

In [67]:
# # ------------------------------------------------------------------
# 1.  Replace the “blank” and “Incertae sedis” values with NaN
#     so that they are automatically ignored by nunique(dropna=True)
# ------------------------------------------------------------------
higher_ranks = ['phylum', 'class', 'order', 'family', 'genus']


ignore_vals = ['', 'Incertae sedis']

# Keep the original data intact – just work on a copy
df_species_clean  = df.replace(ignore_vals, np.nan)

In [68]:
df_species_clean.head()

,taxonID,taxonID_serial,scientificName,acceptedNameUsage,acceptedNameUsageID,kingdom,phylum,class,order,family,genus,specificEpithet,infraSpecificEpithet,scientificNameAuthorship,taxonRank,nameAccordingTo,taxonRemarks,nomenclaturalStatus,taxonomicStatus
0,ed4227734ed75d343320b6a5fd16ce57,NaN,Heterodermia tremulans (Müll. Arg.) W.L. Culb.,NaN,NaN,Fungi,Ascomycota,Lecanoromycetes,Caliciales,Physciaceae,Heterodermia,tremulans,NaN,(Müll. Arg.) W.L. Culb.,species,NaN,NaN,NaN,accepted
1,71ed64cfe69b4dc8b57d08c1e92b9693,1.0,Tetramelas thiopolizus (Nyl.) Giralt & P. Clerc,NaN,NaN,Fungi,Ascomycota,Lecanoromycetes,Caliciales,Caliciaceae,Tetramelas,thiopolizus,NaN,(Nyl.) Giralt & P. Clerc,species,NaN,NaN,NaN,accepted
2,2c6096dc36724669880dc1c58b15c8b7,2.0,Verrucaria gemmifera Taylor,NaN,NaN,Fungi,Ascomycota,Eurotiomycetes,Verrucariales,Verrucariaceae,Verrucaria,gemmifera,NaN,Taylor,species,NaN,NaN,NaN,accepted
3,d42c0868e238baac78bb55b1c3f400b6,3.0,Abrothallus bertianus De Not.,NaN,NaN,Fungi,Ascomycota,Dothideomycetes,Abrothallales,Abrothallaceae,Abrothallus,bertianus,NaN,De Not.,species,"Suija, A.; Hawksworth, D.L. & Pérez-Ortega, S....",NaN,NaN,accepted
4,8a26f1cb1252fcdbe8ef9d3c12cef3d2,4.0,Abrothallus caerulescens I. Kotte,NaN,NaN,Fungi,Ascomycota,Dothideomycetes,Abrothallales,Abrothallaceae,Abrothallus,caerulescens,NaN,I.Kotte,species,"Suija, A.; Hawksworth, D.L. & Pérez-Ortega, S....",NaN,NaN,accepted

### número de nomes

In [69]:
# count unique taxonID (excluding NaN)
unique_taxonid_count = df_species_clean['taxonID'].nunique(dropna=True)
unique_taxonid_count

4440

### numero de taxa aceites

In [70]:
# count unique taxonID where status is 'accepted'
accepted_taxa_unique_count = df_species_clean.loc[df['taxonomicStatus'].fillna('').str.lower() == 'accepted', 'taxonID'].nunique()


accepted_taxa_unique_count

2012

In [71]:
# count occurrences of each taxonRank - total
df_taxonrank_counts = df_species_clean['taxonRank'].value_counts().reset_index()
df_taxonrank_counts.columns = ['taxonRank', 'count']
df_taxonrank_counts

    taxonRank  count
0     species   3605
1     variety    586
2       forma    199
3  subspecies     50

In [72]:
# filter for accepted taxa only
df_accepted = df_species_clean[df_species_clean['taxonomicStatus'].str.lower() == 'accepted'].reset_index(drop=True)
df_accepted.head()
df_accepted.shape

(2012, 19)

In [73]:
# count occurrences of each taxonRank - accepted taxa only
df_taxonrank_counts = df_accepted['taxonRank'].value_counts().reset_index()
df_taxonrank_counts.columns = ['taxonRank', 'count']
df_taxonrank_counts

    taxonRank  count
0     species   1843
1     variety    102
2       forma     47
3  subspecies     20

In [74]:
# count number of families and genus pf accepted taxa
print(f"Number of families in accepted taxa: {df_accepted['family'].nunique()}")
print(f"Number of genera in accepted taxa: {df_accepted['genus'].nunique()}")

Number of families in accepted taxa: 127
Number of genera in accepted taxa: 483

In [75]:
# count occurrences of each taxonRank - accepted taxa only
df_taxonrank_counts = df_accepted['taxonRank'].value_counts().reset_index()
df_taxonrank_counts.columns = ['taxonRank', 'count']
df_taxonrank_counts

    taxonRank  count
0     species   1843
1     variety    102
2       forma     47
3  subspecies     20

In [76]:
# count number of families and genus pf accepted taxa without 'nom. nudum'
print(f"Number of families in accepted taxa: {df_accepted['family'].nunique()}")
print(f"Number of genera in accepted taxa: {df_accepted['genus'].nunique()}")

Number of families in accepted taxa: 127
Number of genera in accepted taxa: 483

In [77]:
# count number of genus that contain only one species
genus_species_counts = df_accepted.groupby('genus')['taxonID'].nunique().reset_index()
genus_with_one_species = genus_species_counts[genus_species_counts['taxonID'] == 1]
print(f"Number of genus that contain only one species: {genus_with_one_species.shape[0]}")

Number of genus that contain only one species: 219

In [78]:
# filter columns for taxonomy tree sunburst plot
df_taxonomy = df_accepted[['kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'scientificName']].copy()
df_taxonomy.head()
df_taxonomy = df_taxonomy.drop_duplicates()
df_taxonomy = df_taxonomy.reset_index(drop=True)
df_taxonomy.head()
df_taxonomy.shape

(2012, 7)

In [79]:
df_taxonomy = df_taxonomy.fillna("inc. sed.")
df_taxonomy = df_taxonomy[df_taxonomy['kingdom'] == "Fungi"].reset_index(drop=True)

In [80]:
df_taxonomy.isna().any()

kingdom           False
phylum            False
class             False
order             False
family            False
genus             False
scientificName    False
dtype: bool

In [81]:
df_taxonomy['sps_count'] = df_taxonomy.groupby('genus')['scientificName'].transform('nunique')

In [82]:
import plotly.express as px


# columns for sunburst plot: family, genus, scientificName
levels = ['class', 'order','family', ]
missing_cols = [c for c in levels if c not in df_accepted.columns]
if missing_cols:
    raise KeyError(f"Missing expected column(s) in df_parts: {missing_cols}")

# prepare aggregated counts, replace missing values with "Unknown"
df_h = df_accepted[levels].fillna("Unknown")
counts = df_h.groupby(levels, as_index=False).size().rename(columns={'size': 'count'})

# create sunburst
fig = px.sunburst(
    counts,
    path=levels,
    values='count',
    color='count',
    color_continuous_scale='Viridis',
)
fig.update_layout(margin=dict(t=40, l=0, r=40, b=0))
fig.update_layout(font_size=36)
fig.update_layout(coloraxis_colorbar_title='Number<br>of species')
fig.show()

In [83]:
# save figure as high-res png
out = os.path.join("../images", "taxonomic_sunburst_highres.png")
fig.write_image(out, format="png", width=2500, height=2000, scale=1)

In [84]:
fig = px.treemap(
    df_taxonomy,
    path=['kingdom', 'phylum', 'class', 'order', 'family', 'genus'],
    maxdepth=3,
    color='family'
)
fig.update_layout(margin=dict(t=0, l=0, r=0, b=0))
fig.update_layout(width=600, height=600)
fig.show()